// Projects/projectItems.js
import { Music, Clipboard, Code, Kanban, MessageCircleQuestion } from "lucide-astro";

const projectItems = [
  {
    icon: Music,
    iconColor: "text-blue-600",
    gradientFrom: "from-blue-100",
    gradientTo: "to-purple-100",
    titleKey: "projects.music.title",
    descriptionKey: "projects.music.description",
    techStack: ["React", "Node.js", "Firebase"],
    liveDemoUrl: "https://youtu.be/axTLGOGyHqE",
    githubUrl: "https://github.com/kopo-k/Hackathon",
  },
  {
    icon: Clipboard,
    iconColor: "text-purple-600",
    gradientFrom: "from-purple-100",
    gradientTo: "to-pink-100",
    titleKey: "projects.multiclip.title",
    descriptionKey: "projects.multiclip.description",
    techStack: ["Electron", "TypeScript", "SQLite", "React"],
    liveDemoUrl: "https://youtu.be/Y_FGdNWNgvk",
    githubUrl: "https://github.com/kopo-k/MultiClip",
  },
  {
    icon: Code,
    iconColor: "text-green-600",
    gradientFrom: "from-green-100",
    gradientTo: "to-teal-100",
    titleKey: "projects.tuioku.title",
    descriptionKey: "projects.tuioku.description",
    techStack: ["Phaser 3", "TypeScript", "Vite", "Docker"],
    liveDemoUrl: "https://tuioku.netlify.app/",
    githubUrl: "https://github.com/vol-14/phaser3_practice",
  },
  {
    icon: Kanban,
    iconColor: "text-orange-600",
    gradientFrom: "from-orange-100",
    gradientTo: "to-amber-100",
    titleKey: "projects.jobhunting.title",
    descriptionKey: "projects.jobhunting.description",
    techStack: ["FuelPHP", "Knockout.js", "MySQL", "Docker"],
    liveDemoUrl: "https://youtu.be/WB8xpwAnGhM",
    githubUrl: "https://github.com/kopo-k/Job_hunting_progress",
  },
  {
    icon: Kanban,
    iconColor: "text-teal-600",
    gradientFrom: "from-teal-100",
    gradientTo: "to-cyan-100",
    titleKey: "projects.daijob.title",
    descriptionKey: "projects.daijob.description",
    techStack: ["React", "Next.js", "TypeScript", "FastAPI", "Supabase", "Docker"],
    liveDemoUrl: "https://youtu.be/4fBMtR1opks",
    githubUrl: "https://github.com/fuharu/Deploy",
  },
  {
    icon: MessageCircleQuestion,
    iconColor: "text-indigo-600",
    gradientFrom: "from-indigo-100",
    gradientTo: "to-violet-100",
    titleKey: "projects.programtokku.title",
    descriptionKey: "projects.programtokku.description",
    techStack: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Docker"],
    liveDemoUrl: "https://program-tokku.vercel.app/",
    githubUrl: "https://github.com/kopo-k/program-tokku",
  },
];

export default projectItems;
