// Projects/projectItems.js
import { Music, Clipboard, Code, Kanban, MessageCircleQuestion } from "lucide-astro";

const projectItems = [
  {
    icon: Music,
    iconColor: "text-blue-600",
    gradientFrom: "from-blue-100",
    gradientTo: "to-purple-100",
    title: "音楽共有アプリ",
    description: "気分や状況、歌詞の種類で曲にタグを付け、他の人が共有した曲を検索できる音楽共有アプリ。",
    techStack: ["React", "Node.js", "Firebase"],
    liveDemoUrl: "https://youtu.be/axTLGOGyHqE",
    githubUrl: "https://github.com/kopo-k/Hackathon",
  },
  {
    icon: Clipboard,
    iconColor: "text-purple-600",
    gradientFrom: "from-purple-100",
    gradientTo: "to-pink-100",
    title: "MultiClip",
    description: "macOS用のクリップボード履歴管理アプリ",
    techStack: ["Electron", "TypeScript", "SQLite", "React"],
    liveDemoUrl: "https://youtu.be/Y_FGdNWNgvk",
    githubUrl: "https://github.com/kopo-k/MultiClip",
  },
  {
    icon: Code,
    iconColor: "text-green-600",
    gradientFrom: "from-green-100",
    gradientTo: "to-teal-100",
    title: "追憶（ついおく）",
    description: "小さい頃の習慣を追体験するブラウザゲーム。ねり消し作り、消しピン、白線の上だけ歩く、スープに浮いている油をつなげるなどの遊びを楽しめます。",
    techStack: ["Phaser 3", "TypeScript", "Vite", "Docker"],
    liveDemoUrl: "https://tuioku.netlify.app/",
    githubUrl: "https://github.com/vol-14/phaser3_practice",
  },
  {
    icon: Kanban,
    iconColor: "text-orange-600",
    gradientFrom: "from-orange-100",
    gradientTo: "to-amber-100",
    title: "就活進捗管理アプリ",
    description: "就活の進捗をカンバン形式で管理できるアプリ",
    techStack: ["FuelPHP", "Knockout.js", "MySQL", "Docker"],
    liveDemoUrl: "https://youtu.be/WB8xpwAnGhM",
    githubUrl: "https://github.com/kopo-k/Job_hunting_progress",
  },
  {
    icon: Kanban,
    iconColor: "text-teal-600",
    gradientFrom: "from-teal-100",
    gradientTo: "to-cyan-100",
    title: "dai-job（だいじょぶ）",
    description: "日程や企業ごとのタスク・書類を一括管理できるアプリ",
    techStack: ["React", "Next.js", "TypeScript", "FastAPI", "Supabase", "Docker"],
    liveDemoUrl: "https://youtu.be/4fBMtR1opks",
    githubUrl: "https://github.com/fuharu/Deploy",
  },
  {
    icon: MessageCircleQuestion,
    iconColor: "text-indigo-600",
    gradientFrom: "from-indigo-100",
    gradientTo: "to-violet-100",
    title: "プログラム特区",
    description: "プログラミングの疑問を解決するQ&Aプラットフォーム。Next.js、Supabase Auth、Dockerで構築。",
    techStack: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Docker"],
    liveDemoUrl: "https://program-tokku.vercel.app/",
    githubUrl: "https://github.com/geek-camp-vol18/program-tokku",
  },
];

export default projectItems;
