// Projects/projectItems.js

const projectItems = [
  {
    image: "/my-portfolio/images/music.webp",
    gradientFrom: "from-blue-100",
    gradientTo: "to-purple-100",
    title: "音楽共有アプリ",
    tag: "Webアプリ",
    role: "フロントエンド",
    description: "気分や状況、歌詞の種類で曲にタグを付け、他の人が共有した曲を検索できる音楽共有アプリ。",
    techStack: ["React", "Node.js", "Firebase"],
    liveDemoUrl: "https://youtu.be/axTLGOGyHqE",
    githubUrl: "https://github.com/kopo-k/Hackathon",
  },
  {
    image: "/my-portfolio/images/multclip.webp",
    gradientFrom: "from-purple-100",
    gradientTo: "to-pink-100",
    title: "MultiClip",
    tag: "デスクトップアプリ",
    role: "個人開発（設計・実装・テスト全て）",
    description: "macOS用のクリップボード履歴管理アプリ",
    techStack: ["Electron", "TypeScript", "SQLite", "React"],
    liveDemoUrl: "https://youtu.be/Y_FGdNWNgvk",
    githubUrl: "https://github.com/kopo-k/MultiClip",
  },
  {
    image: "/my-portfolio/images/tuioku.webp",
    gradientFrom: "from-green-100",
    gradientTo: "to-teal-100",
    title: "追憶（ついおく）",
    tag: "ゲーム",
    role: "Docker環境構築 / CI/CD / タイトル画面・ステージ選択画面 / 白線渡り",
    description: "小さい頃の習慣を追体験するブラウザゲーム。ねり消し作り、消しピン、白線の上だけ歩く、スープに浮いている油をつなげるなどの遊びを楽しめます。",
    techStack: ["Phaser 3", "TypeScript", "Vite", "Docker"],
    liveDemoUrl: "https://tuioku.netlify.app/",
    githubUrl: "https://github.com/vol-14/phaser3_practice",
  },
  {
    image: "/my-portfolio/images/syuukatu.webp",
    gradientFrom: "from-orange-100",
    gradientTo: "to-amber-100",
    title: "就活進捗管理アプリ",
    tag: "Webアプリ",
    role: "個人開発（設計・実装・テスト全て）",
    description: "就活の進捗をカンバン形式で管理できるアプリ",
    techStack: ["FuelPHP", "Knockout.js", "MySQL", "Docker"],
    liveDemoUrl: "https://youtu.be/WB8xpwAnGhM",
    githubUrl: "https://github.com/kopo-k/Job_hunting_progress",
  },
  {
    image: "/my-portfolio/images/good-job.webp",
    gradientFrom: "from-teal-100",
    gradientTo: "to-cyan-100",
    title: "dai-job（だいじょぶ）",
    tag: "Webアプリ",
    role: "バックエンド / Gmail連携 / 通知機能",
    description: "日程や企業ごとのタスク・書類を一括管理できるアプリ",
    techStack: ["React", "Next.js", "TypeScript", "FastAPI", "Supabase", "Docker"],
    liveDemoUrl: "https://youtu.be/4fBMtR1opks",
    githubUrl: "https://github.com/fuharu/Deploy",
  },
  {
    image: "/my-portfolio/images/tokku.webp",
    gradientFrom: "from-indigo-100",
    gradientTo: "to-violet-100",
    title: "プログラム特区",
    tag: "Webアプリ",
    role: "UI設計 / 環境構築（Docker） / 認証認可 / RLSポリシー / フロントエンド（一部） / Vercelデプロイ",
    description: "プログラミングの疑問を解決するQ&Aプラットフォーム。Next.js、Supabase Auth、Dockerで構築。",
    techStack: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Docker"],
    liveDemoUrl: "https://program-tokku.vercel.app/",
    githubUrl: "https://github.com/geek-camp-vol18/program-tokku",
  },
  {
    image: "/my-portfolio/images/VRM_athletic.webp",
    gradientFrom: "from-rose-100",
    gradientTo: "to-pink-100",
    title: "VRMアスレチック",
    tag: "ゲーム",
    role: "個人開発（設計・実装・テスト全て）",
    description: "VRMアバターを操作してアスレチックコースを攻略するタイムアタックゲーム。クリアタイムをランキングで競えます。",
    techStack: ["Unity", "C#", "UniVRM", "Supabase"],
    liveDemoUrl: "https://kopo-k.github.io/vrm-athletic/",
    githubUrl: "https://github.com/kopo-k/vrm-athletic",
  },
  {
    image: "/my-portfolio/images/streamboard.webp",
    gradientFrom: "from-gray-900",
    gradientTo: "to-gray-800",
    title: "StreamBoard",
    tag: "Webアプリ",
    role: "フロントエンド / バックエンド / インフラ",
    description: "YouTube・Twitchの配信を1画面で複数同時に視聴できるマルチストリームビューアー。ドラッグ&ドロップでレイアウトをカスタマイズでき、リアルタイムでチャットの翻訳・盛り上がり分析機能を搭載。",
    techStack: ["React", "Tailwind CSS", "AWS Amplify", "Amazon Bedrock", "DynamoDB"],
    liveDemoUrl: "https://topaz.dev/projects/2e1ff9f4eccc40205e75",
    githubUrl: "https://github.com/progate-hackathon-2026-02/streamboard",
  },
];

export default projectItems;
